@Api_HostAddress = http://localhost:5247

### Obtem todos os acessos
GET {{Api_HostAddress}}/api/data/access_numbers/
Accept: application/json
###

### Envia novo acesso
POST {{Api_HostAddress}}/api/data/new_access
Content-Type: application/json

{
  "IpAddress": "192.168.0.10"
}
###

### Adicionar usuários
POST {{Api_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "firstName": "Guilherme",
  "lastName": "Camikado",
  "email": "guilherme91@email.com",
  "password": "MinhaSenhaSegura123"
}
###

### Retorna token JWT com usuário no mesmo
POST {{Api_HostAddress}}/api/auth/login
Content-Type: application/json
       
{
  "email": "guilherme91@email.com",
  "password": "MinhaSenhaSegura123"
}
###
