POST http://localhost:5247/api/add_user
Content-Type: application/json

{
  "firstName": "Guilherme",
  "lastName": "Camikado",
  "email": "guilherme234@email.com",
  "password": "12345678"
}


# POST http://localhost:5247/api/add_access_management
# Content-Type: application/json

# {
#   "IpAddress":"192.168.0.1"
# }